version: "3.8"

services:
  internsat-backend:
    build:
      context: ./backend
    container_name: internsat-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  internsat-frontend:
    build:
      context: ./frontend
    container_name: internsat-frontend
    depends_on:
      - internsat-backend
    environment:
      - REACT_APP_API_URL=/api
    env_file:
      - ./frontend/.env
    volumes: 
      - ./frontend:/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - internsat-frontend
    restart: unless-stopped