version: "3.8"

services:
  internsat-backend:
    build: ./backend
    container_name: internsat-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  internsat-frontend:
    build: ./frontend
    container_name: internsat-frontend
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - internsat-backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - internsat-frontend
    restart: unless-stopped